// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type LegoSet struct {
	ID           uuid.UUID
	SerialNumber string
	Name         string
	Price        string
	Theme        string
	Year         int32
	TotalParts   int32
	UserID       uuid.UUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Age       int32
	ApiKey    string
}

type UserSet struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	SetID   uuid.UUID
	Price   string
	OwnedAt time.Time
}
